name: Continous Integration
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run goimports
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          output="$($(go env GOPATH)/bin/goimports -l .)"
          test -z $output && exit 0
          $(go env GOPATH)/bin/goimports -d .
          exit 1
      - name: Test
        env:
          GOROOT: ""
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.43.0
          ./bin/golangci-lint run
          go test -v .